services:
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: always
        working_dir: /var/www
        ports:
            - "8000:8000"
        networks:
            - compiler
        depends_on:
            - redis
        environment:
            - APP_ENV=production
            - APP_DEBUG=true
            - APP_KEY=
            - REDIS_HOST=redis
            - REDIS_PORT=6379
            - "REDIS_CHANNEL=code-channel"

    frontend:
        build:
            context: ./frontend
            args:
                REACT_APP_API_URL: http://64.226.66.193:8000
        container_name: react_app
        ports:
            - "3000:80" # nginx exposes port 80
        networks:
            - compiler
        depends_on:
            - backend

    python_executor:
        build: ./workers
        container_name: python_executor
        restart: always
        networks:
            - compiler
        depends_on:
            - redis
        environment:
            - REDIS_URL=redis
            - REDIS_PORT=6379
            - PYTHONUNBUFFERED=1

    redis:
        image: redis:latest
        container_name: redis_db
        restart: always
        networks:
            - compiler
        ports:
            - "6379:6379"

networks:
    compiler:
        driver: bridge
