version: '3.8'

services:
    backend:
        build: .
        container_name: laravel_app
        restart: unless-stopped
        volumes:
            - .:/var/www
        depends_on:
            - redis
        environment:
            - APP_ENV=production
            - DB_CONNECTION=redis
        networks:
            - app_network

    frontend:
        build: ./frontend
        container_name: react_app
        restart: unless-stopped
        ports:
            - "3000:80"
        networks:
            - app_network

    python_executor:
        build: ./workers
        container_name: python_executor
        restart: unless-stopped
        depends_on:
            - redis
        networks:
            - app_network

    redis:
        image: redis:latest
        container_name: redis_db
        restart: unless-stopped
        ports:
            - "6379:6379"
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
